In [62]:
import degiroapi
from degiroapi.product import Product
from degiroapi.order import Order
from degiroapi.utils import pretty_json

degiro = degiroapi.DeGiro()
degiro.login("fabertel", "degEEE333eee")

cashfunds = degiro.getdata(degiroapi.Data.Type.CASHFUNDS)
for data in cashfunds:
    print(data)

EUR 1346.28

In [28]:
# PLACE ORDERS 
# degiro.buyorder(Order.Type.LIMIT,5396380, 3, 3, 147)
# degiro.buyorder(Order.Type.LIMIT,14902751, 3, 7, 57)
degiro.buyorder(Order.Type.LIMIT,4622784, 3, 11, 61)

In [64]:
# EXTRACT ORDERS 
import pandas as pd 
from datetime import datetime, timedelta

orders = degiro.orders(datetime.now() - timedelta(days=4), datetime.now())
orders_log = pd.DataFrame(orders)
orders_log = orders_log.sort_values(["orderId", "last"], ascending = (False, False))

sorted = orders_log.sort_values(by=('last'), ascending=False)
result = sorted.drop_duplicates('orderId', keep='first')
result = result[(result.type=="CREATE")&(result.status=="CONFIRMED")]
result   #isActive=FAlse (processato) , True (still open)

,created,orderId,productId,size,price,buysell,orderTypeId,orderTimeTypeId,stopPrice,currentTradedSize,totalTradedSize,type,status,last,isActive
14,2021-01-11T15:47:27+01:00,5b76ebf9-a80d-42d4-bcfa-f02907f834fa,4622784,11.0,61.0,B,0,3,0.0,0,0,CREATE,CONFIRMED,2021-01-11T15:47:27+01:00,True
10,2021-01-11T15:45:03+01:00,399a3afe-7de4-47fc-a744-fd6916ab4a53,14902751,7.0,57.0,B,0,3,0.0,0,0,CREATE,CONFIRMED,2021-01-11T15:45:04+01:00,False
11,2021-01-11T15:45:03+01:00,b98476a6-a94a-4da1-8164-2321350977d0,5396380,3.0,147.0,B,0,3,0.0,0,0,CREATE,CONFIRMED,2021-01-11T15:45:03+01:00,False

,created,orderId,productId,size,price,buysell,orderTypeId,orderTimeTypeId,stopPrice,currentTradedSize,totalTradedSize,type,status,last,isActive
14,2021-01-11T15:47:27+01:00,5b76ebf9-a80d-42d4-bcfa-f02907f834fa,4622784,11.0,61.0,B,0,3,0.0,0,0,CREATE,CONFIRMED,2021-01-11T15:47:27+01:00,True
10,2021-01-11T15:45:03+01:00,399a3afe-7de4-47fc-a744-fd6916ab4a53,14902751,7.0,57.0,B,0,3,0.0,0,0,CREATE,CONFIRMED,2021-01-11T15:45:04+01:00,False
11,2021-01-11T15:45:03+01:00,b98476a6-a94a-4da1-8164-2321350977d0,5396380,3.0,147.0,B,0,3,0.0,0,0,CREATE,CONFIRMED,2021-01-11T15:45:03+01:00,False